### ISSUE TITLE
This is not working with ext-psr

### ISSUE THREAD

**Issue by JoyceBabu** [laminas/laminas-servicemanager#150]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 3.16

#### Summary

This is not working with [PSR pecl extension](https://pecl.php.net/package/psr), which is at version 1.2

#### Current behavior

Installation fails with error
```
  Problem 1
    - ext-psr is present at version 1.2.0 and cannot be modified by Composer
    - laminas/laminas-servicemanager 3.16.0 conflicts with ext-psr *.
    - Root composer.json requires laminas/laminas-servicemanager ^3.16 -> satisfiable by laminas/laminas-servicemanager[3.16.0].
```

#### How to reproduce

1) ```pecl install psr```
2) ```composer require laminas/laminas-servicemanager  ```

#### Expected behavior

Should be compatible with `ext-psr`

**Comment by Ocramius** [comment]
That is an intentional choice. Refs:

https://github.com/laminas/laminas-servicemanager/blob/f32cdaea6dcba17b5701e46455a80ce4006970cb/composer.json#L56

https://github.com/laminas/laminas-servicemanager/blame/f32cdaea6dcba17b5701e46455a80ce4006970cb/composer.json#L56

https://github.com/laminas/laminas-servicemanager/commit/2ca79274c34ae2223ccdbe8f5fe5f4b7bff82d64

https://github.com/laminas/laminas-servicemanager/issues/124

https://github.com/laminas/laminas-servicemanager/pull/125

https://github.com/jbboehr/php-psr/issues/87
